### ISSUE TITLE
Pre-release for 0.7 

### ISSUE THREAD

**Issue by paf31** [pelotom/purescript-easy-ffi#2]
I'd like to use the latest version in `master` to make a prerelease version of `yargs`. Could you please make a pre-release tag of `master`?

**Comment by pelotom** [comment]
Sure, here you go: [`purescript-0.7-prerelease`](https://github.com/pelotom/purescript-easy-ffi/releases/tag/purescript-0.7-prerelease).

**Comment by paf31** [comment]
:bow:
