### ISSUE TITLE
Please consider PR for 0.9.1 support

### ISSUE THREAD

**Issue by kika** [pelotom/purescript-easy-ffi#4]
Easy-FFI doesn't work with 0.9.1 from the box, please consider PR #3

**Comment by pelotom** [comment]
Fixed by merging #3

**Comment by kika** [comment]
@pelotom Could you please push a new version tag? Bower doesn't pick it up.

**Comment by pelotom** [comment]
[Done](https://github.com/pelotom/purescript-easy-ffi/releases/tag/v2.0.0).
